AWSTemplateFormatVersion: '2010-09-09'
Description: Example using the Multiply Macro to create multiple resources

Parameters:
  InstanceCount:
    Type: Number
    Description: Number of instances to create
    Default: 4

Resources:
  S3:
    Type: AWS::S3::Bucket
    MultiplyKey: Instances
    Properties:
      BucketName: "multitest-%d-bucket"

  Fn::Transform:
    Name: TUMultiplyMacro
    Parameters:
      Multiply: !Ref InstanceCount
      MultiplyKey: Instances
  SQS:
    Type: AWS::SQS::Queue
    MultiplyKey: Instances
    
