AWSTemplateFormatVersion: '2010-09-09'
Description: Example using the Multiply Macro to create multiple resources

Parameters:
  InstanceCount:
    Type: Number
    Description: Number of instances to create
    Default: 4

Resources:
  Fn::Transform:
    Name: TUMultiply
    Parameters:
      Multiply: !Ref InstanceCount
      MultiplyKey: Instances

  S3:
    Type: AWS::S3::Bucket
    MultiplyKey: Instances
    Properties:
      BucketName: "multitest-bucket-%d"

  SQS:
    Type: AWS::SQS::Queue
    MultiplyKey: Instances
    
