AWSTemplateFormatVersion: '2010-09-09'
Description: Register TU Delft's Macro's. You only need to run this once in your account.

Resources:
  MacroRegistration:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: TU-Delft-Macro-Registration
      #FunctionName: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:TU-Delft-Macro-Function'
      FunctionName: arn:aws:lambda:eu-central-1:752522825262:function:CountMacroFunction:CountMacroFunctionProductionVersion
      Description: Register TU Delft's Macro for use in CloudFormation templates