AWSTemplateFormatVersion: '2010-09-09'
Description: Register TU Delft's Macro's. You only need to run this once in your account.

Resources:
  TUMultiplyTransform:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: TUMultiply
      FunctionName: arn:aws:lambda:eu-central-1:752522825262:function:MultiplyTransformFunction
      Description: Register TU Delft's Multiply transformation for use in CloudFormation templates